services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend.dev
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    develop:
      watch:
        - action: sync
          path: ./backend/
          target: /app
          ignore:
            - node_modules/
            - dist/
        - action: rebuild
          path: ./backend/package.json
        - action: rebuild
          path: ./backend/.env
        - action: rebuild
          path: ./backend/prisma/schema.prisma
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend.dev
    ports:
      - "3001:3001"
    develop:
      watch:
        - action: sync
          path: ./frontend/
          target: /app
          ignore:
            - node_modules/
            - .next/
        - action: rebuild
          path: ./frontend/package.json
