# base container
FROM node:22-alpine

WORKDIR /app

COPY backend/package*.json backend/pnpm-lock.yaml ./

RUN npm install -g pnpm node-gyp

RUN pnpm install

COPY backend/ ./

RUN pnpm prisma generate

ARG PORT=3000

ENV PORT=${PORT}

EXPOSE ${PORT}

CMD [ "pnpm", "start:dev" ]
