export const PERMISSION_CODE = {
  VIEW_USER: 'VIEW_USER',
  EDIT_USER: 'EDIT_USER',

  VIEW_USER_CREDENTIAL: 'VIEW_USER_CREDENTIAL',
  EDIT_USER_CREDENTIAL: 'EDIT_USER_CREDENTIAL',

  VIEW_PERMISSION: 'VIEW_PERMISSION',
  EDIT_PERMISSION: 'EDIT_PERMISSION',

  VIEW_ROLE: 'VIEW_ROLE',
  EDIT_ROLE: 'EDIT_ROLE',

  VIEW_ROLE_PERMISSION: 'VIEW_ROLE_PERMISSION',
  EDIT_ROLE_PERMISSION: 'EDIT_ROLE_PERMISSION',

  VIEW_USER_ROLE: 'VIEW_USER_ROLE',
  EDIT_USER_ROLE: 'EDIT_USER_ROLE',
} as const;
